security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            user_checker: App\Security\UserChecker
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10