security:
    # Define how passwords are hashed
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # Change to "username" if needed

        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true # Replace "anonymous: lazy" with "lazy: true"
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home # Redirect to home page on successful login
                username_parameter: _username
                password_parameter: _password
                failure_path: app_login # Redirect to login page on failure
            logout:
                path: app_logout
                target: app_home # Redirect on logout

    access_control:
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
    