controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\ForumController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_forgot_password:
    path: /forgot-password
    controller: App\Controller\ForgotController::request

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::profile

app_category_show:
    path: /category/{id}
    controller: App\Controller\ForumController::showCategory

app_topic_new:
    path: /topic/new
    controller: App\Controller\ForumController::newTopic

app_topic_show:
    path: /topic/{id}
    controller: App\Controller\ForumController::showTopic

