controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_category_show:
    path: /category/{id}
    controller: App\Controller\ForumController::showCategory

app_topic_new:
    path: /topic/new
    controller: App\Controller\ForumController::newTopic

app_topic_show:
    path: /topic/{id}
    controller: App\Controller\ForumController::showTopic

