controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\ForumController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_logout: 
    path: /logout
    controller: App\Controller\RegistrationController::logout

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_confirmation_email:
    path: /confirmation-email
    controller: App\Controller\RegistrationController::confirmationEmail


app_confirmation_email_success:
    path: /confirmation-success
    controller: App\Controller\RegistrationController::confirmationSuccess

app_forgot_password:
    path: /forgot-password
    controller: App\Controller\ForgotController::request

app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ForgotController::reset

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::profile

app_remove_profile_picture:
    path: /profile/remove-picture
    controller: App\Controller\ProfileController::removeProfilePicture
    
app_category_show:
    path: /category/{id}
    controller: App\Controller\ForumController::showCategory

app_topic_new:
    path: /topic/new
    controller: App\Controller\ForumController::newTopic

app_topic_show:
    path: /topic/{id}
    controller: App\Controller\ForumController::showTopic

