# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile-pictures'

services:
    # Automatically injects dependencies in your services.
    App\Security\LoginFormAuthenticator:
        autowire: true
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Controller\ProfileController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $fileUploader: '@App\Service\FileUploader'
            $passwordManager: '@App\Service\PasswordManagementService'


    App\Twig\TimeAgoExtension:
        tags: ['twig.extension']
    # Make classes in the src/ folder available as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
